name: rl-timelapses
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pytorch
  - pytorch-cuda=12.4  # remove this line if you only want CPU
  - pip
  - pip:
      - gymnasium[all]
      - setproctitle
      - tensorboard
      - moviepy